# ReadME
# Here, it's some example to create docker-compose



version: "3"
services:

  # NodeJs Server      
  appnode:
    container_name: appNode
    hostname: appNode
    build:
      context: ./appNode/
      dockerfile: Dockerfile_node
    volumes:
      - './appNode:/appNode'
    depends_on:
      - "mongo"
    ports:
      - '3002:3002'
    networks:
      - default

  # React Application
  appreact:
    container_name: appReact
    hostname: appReact
    build:
      context: ./appReact/
      dockerfile: Dockerfile_react
    volumes:
      - './appReact:/appReact'
    ports:
      - '3000:3000'
    networks:
      - default


  # Mongo Database
  mongo:
    container_name: mongo
    hostname: mongo
    build:
      context: ./mongo/
      dockerfile: Dockerfile_mongo
    ports:
      - '27017:27017'
    volumes:
      - './mongo/db:/data/db'
    networks:
      - default

        
  # PlayFramework 
  # TODO
 
  # Firefox Application
  firefox:
    container_name: firefox
    hostname: firefox
    build:
      context: ./firefox/
      dockerfile: Dockerfile_firefox
    depends_on:
      - "appreact"
      - "appnode"
    volumes:
      - '/tmp/.X11-unix:/tmp/.X11-unix'
    environment:
      - DISPLAY=$DISPLAY
    networks:
      - default

networks:
    default:
