version: "3.7"
services:

  proxy:
    volumes:
      - ./assets/:/www/assets/
    build:
      context: ./proxy/
      args:
        PROXY_URL: ${PROXY_URL:-http://localhost}
    ports:
        - ${PROXY_PORT:-127.0.0.1:80}:80
    networks:
      - proxy
    depends_on:
      - service_alumni
      - front_login

  service_user_node:
    build:  ./service_user/server/
    ports: 
      - 8081:8080

  #Mongo database
  service_user_database:
    image: mongo:4.2.1
    volumes:
      - service_user_database_db:/data/db
      - service_user_database_configdb:/data/configdb

  service_alumni:
    build:  ./service-alumni/
    networks:
      - proxy
      - internal_alumni
    depends_on:
      - database_alumni

  database_alumni:
    build:  ./database-mongodb/
    environment:
      - IMPORT_DB=alumnis
      - IMPORT_COLLECTION=alumnis
    volumes:
      - ./service-alumni/database/alumnis.json:/tmp/data.json
      - database_alumni_db:/data/db
      - database_alumni_configdb:/data/configdb
    networks:
      - internal_alumni

  # Service Front   
  front_login:
    hostname: localhost
    build:
      context: ./front-login1/
      args:
        BASE_HREF: /hello/
    networks:
      - proxy

volumes:
  service_user_database_db:
  service_user_database_configdb:
  database_alumni_db:
  database_alumni_configdb:

networks:
  proxy:
  internal_alumni: