# ReadME
# Here, it's some example to create docker-compose



version: "3"
services:


  # Mongo Database
  service_user_db:
    build:
      context: ./service_user/db/


  # Service Front   
  front_login:
    hostname: localhost
    build:
      context: ./front-login1/
    volumes:
      - './front-login1:/angular'
    ports:
      - '4200:80'

