# ReadME
# Here, it's some example to create docker-compose



version: "3"
services:
    proxy:
      image: nginx:1.17.4-alpine
      volumes:
        - ./proxy/default.conf:/etc/nginx/conf.d/default.conf
        - ./assets/:/www/assets/
      ports:
        - 80:80
