version: "3.7"
services:

  proxy:
    volumes:
      - ./assets/:/www/assets/
    ports:
        - ${PROXY_PORT:-127.0.0.1:80}:80
    build:
      context: ./proxy/
      args:
        PROXY_URL: ${PROXY_URL:-http://localhost}

  service_user_node:
    build:  ./service_user/server/
    ports: 
      - 8081:8080

  #Mongo database
  service_user_database:
    image: mongo:4.2.1
    volumes:
      - service_user_database_db:/data/db
      - service_user_database_configdb:/data/configdb

  service_alumni_database:
    image: mongo:4.2.1
    volumes:
      - service_alumni_database_db:/data/db
      - service_alumni_database_configdb:/data/configdb

  # Service Front   
  front_login:
    hostname: localhost
    build:
      context: ./front-login1/
      args:
        BASE_HREF: /hello/

volumes:
  service_user_database_db:
  service_user_database_configdb:
  service_alumni_database_db:
  service_alumni_database_configdb:
