version: "3.7"
services:

  proxy:
    volumes:
      - ./assets/:/www/assets/
    build:
      context: ./proxy/
      args:
        PROXY_URL: ${PROXY_URL:-http://localhost}
    ports:
        - ${PROXY_PORT:-127.0.0.1:80}:80
    networks:
      - proxy
  #Mongo database

  service_connexion:
    build: ./service-connexion/
    networks:
      - proxy
    env_file:
      - ./.env/api.env

  service_link:
    build: ./service-link/
    networks:
      - proxy
    environment:
      - PROXY_URL=${PROXY_URL:-http://localhost}

  service_user:
    build: ./service-user/
    networks:
      - proxy
      - internal_user
    depends_on:
      - database_user
    env_file:
      - ./.env/api.env

  database_user:
    build: ./database-mongodb/
    environment:
      - IMPORT_DB=users
      - IMPORT_COLLECTION=users
    volumes:
      - ./service-user/database/users.json:/tmp/data.json
      - database_user_db:/data/db
      - database_user_configdb:/data/configdb
    networks:
      - internal_user

  service_alumni:
    build:  ./service-alumni/
    networks:
      - proxy
      - internal_alumni
    depends_on:
      - database_alumni
    env_file:
      - ./.env/api.env

  database_alumni:
    build:  ./database-mongodb/
    environment:
      - IMPORT_DB=alumnis
      - IMPORT_COLLECTION=alumnis
    volumes:
      - ./service-alumni/database/alumnis.json:/tmp/data.json
      - database_alumni_db:/data/db
      - database_alumni_configdb:/data/configdb
    networks:
      - internal_alumni

  service_scrapping:
    build: ./service-scrapping/
    networks: 
      - proxy

  # Service Front   

  service_stats:
    build:  ./service-stats/
    networks:
      - proxy

  # Service Front   
  service_logs:
    build:  ./service-logs/
    networks:
      - proxy
      - internal_logs
    depends_on:
      - database_logs

  database_logs:
    image: mysql:5.7
    environment:
       MYSQL_ROOT_PASSWORD: somelogs
       MYSQL_DATABASE: logs
       MYSQL_USER: logs
       MYSQL_PASSWORD: logs
    networks:
      - internal_logs

  front:
    build:
      context: ./front/
      args:
        BASE_HREF: /
    networks:
      - proxy

  # Service Mail
  service_mail:
    build: ./service-mail/
    networks:
      - proxy
    environment:
      - PROXY_URL= ${PROXY_URL:-http://localhost}

volumes:
  database_user_db:
  database_user_configdb:
  database_alumni_db:
  database_alumni_configdb:
  database_logs:

networks:
  proxy:
  internal_alumni:
  internal_user:
  internal_logs:
