version: "3.7"
services:

  proxy:
    volumes:
      - ./assets/:/www/assets/
    build:
      context: ./proxy/
      args:
        PROXY_URL: ${PROXY_URL:-http://localhost}
    ports:
        - ${PROXY_PORT:-127.0.0.1:80}:80
    networks:
      - proxy
  #Mongo database

  service_user:
    build: ./service-user/
    networks:
      - proxy
      - internal_user
    depends_on:
      - database_user

  database_user:
    build: ./database-mongodb/
    environment:
      - IMPORT_DB=users
      - IMPORT_COLLECTION=users
    volumes:
      - ./service-user/database/users.json:/tmp/data.json
      - database_user_db:/data/db
      - database_user_configdb:/data/configdb
    networks:
      - internal_user

  service_alumni:
    build:  ./service-alumni/
    networks:
      - proxy
      - internal_alumni
    depends_on:
      - database_alumni

  database_alumni:
    build:  ./database-mongodb/
    environment:
      - IMPORT_DB=alumnis
      - IMPORT_COLLECTION=alumnis
    volumes:
      - ./service-alumni/database/alumnis.json:/tmp/data.json
      - database_alumni_db:/data/db
      - database_alumni_configdb:/data/configdb
    networks:
      - internal_alumni

  service_logs:
    build:  ./service-logs/
    networks:
      - proxy

  # Service Front   
  front:
    build:
      context: ./front/
      args:
        BASE_HREF: /hello/
    networks:
      - proxy

volumes:
  database_user_db:
  database_user_configdb:
  database_alumni_db:
  database_alumni_configdb:

networks:
  proxy:
  internal_alumni:
  internal_user:
