# base image
FROM mongo:4.2.0 

# set working directory
WORKDIR /data


# Define mountable directories.
VOLUME ["/data/db"]

# Define working directory.


CMD ["mongod","--port","27017","--bind_ip","0.0.0.0"]

# Expose ports.
#   - 27017: process
#   - 28017: http
EXPOSE 27017
#EXPOSE 28017

