name: Continuous Deployment

on: 
  push:
    branches: 
      - dev
  check_run:
    types: [rerequested]
    branches:
      - dev

jobs:
  deployment:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@f6ce2af
      with:
        ref: ${{ github.ref }}

    - name: Build docker-compose
      run: ./install.sh && docker-compose build

    - name: Run deploy script
      uses: maddox/actions/ssh@064c408
      with:
        args: "cd ~/graduate-follow-up/
          && git fetch 
          && git checkout ${{ github.sha }}
          &&
            PROXY_PORT=${{ secrets.PROXY_PORT }} \
            PROXY_URL=${{ secrets.PROXY_URL }} \
            ./deploy.sh"
      env:
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        HOST: ${{ secrets.MACHINE_HOST }}
        USER: ${{ secrets.USER }}
